---
subtitle: "TrueBlocks Explorer output"
date: "5/30/2019"
params:
  filepath: "data/output.csv"
  address: "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359"
  name: "Aragon Dream DAO Party"
always_allow_html: yes
output:
  pdf_document:
    toc: yes
  html_document:
    df_print: paged
    includes:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(scales)
```

```{r}
params
data.set <- read_csv(params$filepath) %>%
  mutate(Date = as.POSIXct(Date, format="%m/%d/%Y %H:%M:%S")) %>%
#  mutate(FunctionName = ifelse(is.na(FunctionName), "NA", FunctionName)) %>%
  mutate(FromName = ifelse(is.na(FromName), From, FromName)) %>%
  return()
```


## ETH In/Out

```{r message=FALSE, warning=FALSE, fig.align='center'}
data.set %>%
  mutate(Type = ifelse(To == params$address, "In", ifelse(From == params$address, "From", "Other"))) %>%
  filter(Type %in% c("In", "Out")) %>%
  mutate(Date = as.Date(Date)) %>%
  mutate(EtherValue = ifelse(Type == "Out", -EtherValue, EtherValue)) %>%
  group_by(Type, Date) %>%
  summarize(val = sum(EtherValue)) %>%
  mutate(cumval = cumsum(val)) %>%
  ggplot(aes(x=Date, y=cumval, color=Type)) +
  geom_line() +
  labs(title="Ether In/Out", y="Cumulative Ether In/Out")

data.set %>%
  filter(To == params$address) %>%
  group_by(From) 

data.set %>%
  filter(To == params$address) %>%
  ggplot(aes(x=BlockNumber, fill=FunctionName)) +
  geom_histogram() +
  scale_x_continuous(labels = comma) +
  labs(title = paste0("Functions called on address ", params$address))


top10 <- data.set %>%
  filter(To == params$address) %>%
  group_by(FromName) %>%
  summarize(count = n()) %>%
  top_n(10, count) %>%
  select(FromName) %>%
  unlist() %>%
  unname()
```

```{r message=FALSE, fig.align='center', fig.width=10}
data.set %>%
  filter(To == params$address) %>%
  filter(FromName %in% top10) %>%
  ggplot(aes(x=Date, y=FunctionName, color=FromName)) +
  geom_point() +
  facet_wrap(facets = 'FromName') +
  # scale_y_discrete(limits=rev(c('startAuction', 'startAuctions', 'startAuctionsAndBid', 'newBid', 'unsealBid', 'finalizeAuction', 'transfer', 'invalidateName'))) +
  theme(legend.position="none") +
  labs(title = paste0("Function timeline for top 10 users (ranked by appearance count)"))


```

---
title: `r params$name`
---
